// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7cgAi_lfV3a7YCwNcff2j8BpMh5OHsA',
    appId: '1:717815003689:web:ff094d04e1a41f32bcba38',
    messagingSenderId: '717815003689',
    projectId: 'flower-pvlzs9',
    authDomain: 'flower-pvlzs9.firebaseapp.com',
    storageBucket: 'flower-pvlzs9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8OYVahm0AjMGEltQjzskhaj9X1b9mX2k',
    appId: '1:475793784963:android:e1b4bde37c024e8c93dbb6',
    messagingSenderId: '475793784963',
    projectId: 'flower2-8f66e',
    storageBucket: 'flower2-8f66e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGqeqyUKYuDGZG5HxvUZ5CTpZmoDiaD6M',
    appId: '1:717815003689:ios:570066c1e58f499bbcba38',
    messagingSenderId: '717815003689',
    projectId: 'flower-pvlzs9',
    storageBucket: 'flower-pvlzs9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGqeqyUKYuDGZG5HxvUZ5CTpZmoDiaD6M',
    appId: '1:717815003689:ios:570066c1e58f499bbcba38',
    messagingSenderId: '717815003689',
    projectId: 'flower-pvlzs9',
    storageBucket: 'flower-pvlzs9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ7cgAi_lfV3a7YCwNcff2j8BpMh5OHsA',
    appId: '1:717815003689:web:faf302dadf2e92dbbcba38',
    messagingSenderId: '717815003689',
    projectId: 'flower-pvlzs9',
    authDomain: 'flower-pvlzs9.firebaseapp.com',
    storageBucket: 'flower-pvlzs9.appspot.com',
  );

}